WDDN1/Controllers/ViewMarkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WDDN1.Models;

namespace WDDN1.Controllers
{
    
    public class ViewMarkController : Controller
    {
        private Model1 db = new Model1();

        public ActionResult Index()
        {
            ViewBag.StudentId = new SelectList(db.Students, "StudentID", "Fullname");
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            //RedirectToAction();
            return View();
        }
        
        [HttpPost]
        public ActionResult ViewM()
        {
            int id = int.Parse(Request["StudentId"]);

            var studentMarks = (from m in db.Marks where m.StudentId == id select m).ToList();

            return View(studentMarks);
        }
        
        
    }
}

WDDN1/Views/ViewMark/Details.cshtml
@model IEnumerable<WDDN1.Models.Mark>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.course.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.student.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.marks)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.student.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.marks)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>

WDDN1/Views/ViewMark/Index.cshtml
@model WDDN1.Models.Mark
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


@using (Html.BeginForm("ViewM","ViewMark",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mark</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="View Your Marks" class="btn btn-default" />
            </div>
        </div>


</div>
}

WDDN1/Views/ViewMark/Index1.cshtml
@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index1</h2>

WDDN1/Views/ViewMark/IndexMarksView.cshtml
@model WDDN1.Models.Mark
@model IEnumerable<WDDN1.Models.Mark>
@{
    ViewBag.Title = "IndexMarksView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IndexMarksView</h2>
<h2>Index</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.course.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.student.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.marks)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.student.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.marks)
            </td>
           
        </tr>
    }

</table>

WDDN1/Views/ViewMark/ViewM.cshtml
@model IEnumerable<WDDN1.Models.Mark>

@{
    ViewBag.Title = "ViewM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<environment names="Development">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</environment>
<h2>Result</h2>
<table class="striped hoverable animated bounceInLeft" >
    <tr>
        <th><blockquote>Subjects</blockquote></th>
        <th><blockquote>Marks</blockquote></th>
    </tr>
    @{
        int count = 0;
        double total = 0;
        foreach (var m in Model)
        {
            count += 1;
            total += m.marks;
            <tr>
                <td> @Html.DisplayFor(modelItem => m.course.CourseName)</td>
                <td>@Html.DisplayFor(modelItem => m.marks)</td>
            </tr>
        }

        double average = total / count;
    }
   
</table>
<blockquote>
    <h3 class="center-align teal-text darken4 animated zoomIn">
        @average Is Your Average Performance!
    </h3>
</blockquote>